### ISSUE TITLE
1.4.0: Livelock in SearchModel in case of ConcurrentManager

### ISSUE THREAD

**Issue by sszuev** [avicomp/ont-api#71]
Unfortunately, this silly mistake has penetrated the release (1.4.0).
The following trivial testcase almost always leads to livelock:

```
OWLOntologyDocumentSource src = ReadWriteUtils.getDocumentSource("/ontapi/family.ttl", OntFormat.TURTLE);
OWLOntologyManager m = OntManagers.createConcurrentONT();
OWLOntology o = m.loadOntologyFromOntologyDocument(src);
Assert.assertEquals(58, o.classesInSignature().count());

```

Stacktrace: 

```
"main" #1 prio=5 os_prio=0 tid=0x00000000022ac000 nid=0x5a8 runnable [0x000000000273a000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap.java:2426)
	- locked <0x00000000d8de3a20> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2288)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1936)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at ru.avicomp.ontapi.internal.InternalCache$CaffeineWrapper.get(InternalCache.java:480)
	at ru.avicomp.ontapi.internal.SearchModel$CachedFactory.canWrap(SearchModel.java:210)
	at ru.avicomp.ontapi.jena.impl.conf.BaseFactoryImpl.wrap(BaseFactoryImpl.java:105)
	at org.apache.jena.enhanced.Personality.newInstance(Personality.java:94)
	at org.apache.jena.enhanced.EnhGraph.getNodeAs(EnhGraph.java:121)
	at ru.avicomp.ontapi.jena.impl.UnionModel.getNodeAsInternal(UnionModel.java:186)
	at ru.avicomp.ontapi.jena.impl.UnionModel.fetchNodeAs(UnionModel.java:172)
	at ru.avicomp.ontapi.internal.SearchModel.fetchNodeAs(SearchModel.java:164)
	at ru.avicomp.ontapi.jena.impl.PersonalityModel.canAs(PersonalityModel.java:116)
	at ru.avicomp.ontapi.jena.impl.OntCEImpl$ClassExpressionFactory.hasType(OntCEImpl.java:1173)
	at ru.avicomp.ontapi.jena.impl.OntCEImpl$ClassExpressionFactory.lambda$isObjectOfType$2(OntCEImpl.java:1169)
	at ru.avicomp.ontapi.jena.impl.OntCEImpl$ClassExpressionFactory$$Lambda$502/426070939.test(Unknown Source)
	at org.apache.jena.util.iterator.FilterIterator.hasNext(FilterIterator.java:56)
	at ru.avicomp.ontapi.jena.utils.Iter.findFirst(Iter.java:245)
	at ru.avicomp.ontapi.jena.impl.OntCEImpl$ClassExpressionFactory.isObjectOfType(OntCEImpl.java:1169)
	at ru.avicomp.ontapi.jena.impl.OntCEImpl$ClassExpressionFactory.map(OntCEImpl.java:1235)
	at ru.avicomp.ontapi.jena.impl.OntCEImpl$ClassExpressionFactory.canWrap(OntCEImpl.java:1201)
	at ru.avicomp.ontapi.internal.SearchModel$CachedFactory.lambda$canWrap$0(SearchModel.java:210)
	at ru.avicomp.ontapi.internal.SearchModel$CachedFactory$$Lambda$469/1217741734.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$36/489411441.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x00000000d8de3a20> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at ru.avicomp.ontapi.internal.InternalCache$CaffeineWrapper.get(InternalCache.java:480)
	at ru.avicomp.ontapi.internal.SearchModel$CachedFactory.canWrap(SearchModel.java:210)
	at ru.avicomp.ontapi.jena.impl.conf.BaseFactoryImpl.wrap(BaseFactoryImpl.java:105)
	at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:152)
	at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:31)
	at org.apache.jena.enhanced.Polymorphic.asInternal(Polymorphic.java:62)
	at org.apache.jena.enhanced.EnhNode.viewAs(EnhNode.java:102)
	at org.apache.jena.enhanced.EnhGraph.getNodeAs(EnhGraph.java:126)
	at ru.avicomp.ontapi.jena.impl.UnionModel.getNodeAsInternal(UnionModel.java:186)
	at ru.avicomp.ontapi.jena.impl.UnionModel.fetchNodeAs(UnionModel.java:172)
	at ru.avicomp.ontapi.internal.SearchModel.fetchNodeAs(SearchModel.java:164)
	at ru.avicomp.ontapi.jena.impl.PersonalityModel.canAs(PersonalityModel.java:116)
	at ru.avicomp.ontapi.jena.impl.OntListImpl$3.isValid(OntListImpl.java:180)
	at ru.avicomp.ontapi.jena.impl.OntListImpl$$Lambda$496/1095849663.test(Unknown Source)
	at org.apache.jena.util.iterator.FilterIterator.hasNext(FilterIterator.java:56)
	at org.apache.jena.util.iterator.Map1Iterator.hasNext(Map1Iterator.java:49)
	at org.apache.jena.util.iterator.Map1Iterator.hasNext(Map1Iterator.java:49)
	at org.apache.jena.util.iterator.NiceIterator.asSet(NiceIterator.java:208)
	at org.apache.jena.util.iterator.NiceIterator.toSet(NiceIterator.java:199)
	at ru.avicomp.ontapi.internal.ReadHelper.calcClassExpression(ReadHelper.java:382)
	at ru.avicomp.ontapi.internal.ReadHelper.calcClassExpression(ReadHelper.java:306)
	at ru.avicomp.ontapi.internal.ReadHelper.calcClassExpression(ReadHelper.java:306)
	at ru.avicomp.ontapi.internal.ReadHelper.lambda$calcClassExpression$7(ReadHelper.java:381)
	at ru.avicomp.ontapi.internal.ReadHelper$$Lambda$498/1257532915.apply(Unknown Source)
	at org.apache.jena.util.iterator.Map1Iterator.next(Map1Iterator.java:46)
	at org.apache.jena.util.iterator.NiceIterator.asSet(NiceIterator.java:208)
	at org.apache.jena.util.iterator.NiceIterator.toSet(NiceIterator.java:199)
	at ru.avicomp.ontapi.internal.ReadHelper.calcClassExpression(ReadHelper.java:382)
	at ru.avicomp.ontapi.internal.NoCacheObjectFactory.get(NoCacheObjectFactory.java:55)
	at ru.avicomp.ontapi.internal.axioms.EquivalentClassesTranslator.toAxiom(EquivalentClassesTranslator.java:55)
	at ru.avicomp.ontapi.internal.AxiomTranslator.lambda$translate$0(AxiomTranslator.java:93)
	at ru.avicomp.ontapi.internal.AxiomTranslator$$Lambda$468/556945462.apply(Unknown Source)
	at org.apache.jena.util.iterator.Map1Iterator.next(Map1Iterator.java:46)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at ru.avicomp.ontapi.internal.axioms.AbstractNaryTranslator.listAxioms(AbstractNaryTranslator.java:98)
	at ru.avicomp.ontapi.internal.InternalModel.lambda$createAxiomTriplesMap$23(InternalModel.java:942)
	at ru.avicomp.ontapi.internal.InternalModel$$Lambda$453/1899567935.get(Unknown Source)
	at ru.avicomp.ontapi.internal.CacheObjectTriplesMapImpl.loadMap(CacheObjectTriplesMapImpl.java:96)
	at ru.avicomp.ontapi.internal.InternalModel$1.loadMap(InternalModel.java:979)
	at ru.avicomp.ontapi.internal.CacheObjectTriplesMapImpl$$Lambda$409/1598434875.apply(Unknown Source)
	at ru.avicomp.ontapi.internal.InternalCache$$Lambda$366/874740624.load(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3366)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache$$Lambda$35/2092709730.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$36/489411441.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x00000000d8cffb70> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at ru.avicomp.ontapi.internal.InternalCache$CaffeineWrapper$1.get(InternalCache.java:493)
	at ru.avicomp.ontapi.internal.CacheObjectTriplesMapImpl.getMap(CacheObjectTriplesMapImpl.java:125)
	at ru.avicomp.ontapi.internal.CacheObjectTriplesMapImpl.objects(CacheObjectTriplesMapImpl.java:148)
	at ru.avicomp.ontapi.internal.InternalModel$$Lambda$454/1106468732.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at ru.avicomp.ontapi.internal.InternalModel.flatMap(InternalModel.java:680)
	at ru.avicomp.ontapi.internal.InternalModel.listOWLAxioms(InternalModel.java:573)
	at ru.avicomp.ontapi.internal.InternalModel.readOWLObjects(InternalModel.java:461)
	at ru.avicomp.ontapi.internal.InternalModel$$Lambda$369/521331027.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$36/489411441.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x00000000d89497b0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at ru.avicomp.ontapi.internal.InternalCache$CaffeineWrapper.get(InternalCache.java:480)
	at ru.avicomp.ontapi.internal.InternalCache$CaffeineWrapper$2.get(InternalCache.java:505)
	at ru.avicomp.ontapi.internal.InternalModel.listOWLObjects(InternalModel.java:447)
	at ru.avicomp.ontapi.internal.InternalModel.listOWLClasses(InternalModel.java:399)
	at ru.avicomp.ontapi.OntBaseModelImpl.classesInSignature(OntBaseModelImpl.java:191)
	at ru.avicomp.ontapi.OWLOntologyWrapper$$Lambda$406/1450712470.get(Unknown Source)
	at ru.avicomp.ontapi.RWLockedOntology.withReadLockToObject(RWLockedOntology.java:115)
	at ru.avicomp.ontapi.OWLOntologyWrapper.classesInSignature(OWLOntologyWrapper.java:413)
	at ru.avicomp.ontapi.tmp.Tmp_LockPizza.main(Tmp_LockPizza.java:35)
```

What's going on here ? A `SearchModel` nodes cache uses caffeine in case the manager is concurrent (`OntManagers.createConcurrentONT()`), caffeine uses `ConcurrentHashMap` that does not support recursive computations. 
See also https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations
And https://stackoverflow.com/questions/32678692/live-lock-in-concurrenthashmap

No lucky.

Fortunately theres is a somple fix: just switching to LHM based cache, although it may degrade performance for concurrent mode somehow.

**Comment by sszuev** [comment]
fixed.

**Comment by ben-manes** [comment]
fyi, the `addCount` live-lock is detected in jdk12 and throws an `IllegalStateException`. This would still fail, but at least does so loudly rather than spin silently.
